version: '3'
services:

  web:
    image: artemryzhov/php-apache-dev:7.3
    volumes:
      - .:/app
    env_file: .env.example
    networks:
      - internal
    working_dir: /app/project
    ports:
      - 9020:80

  mysql:
    image: mysql:5.6
    networks:
      - internal
    env_file: .env.example
    volumes:
      - ./.db:/var/lib/mysql
    expose:
      - 3306:3306

  mailhog:
    image: mailhog/mailhog
    networks:
      - internal
    env_file: .env.example
    user: root
    environment:
      - MH_API_BIND_ADDR=0.0.0.0:80
      - MH_UI_BIND_ADDR=0.0.0.0:80
    expose:
      - 80
    ports:
      - 8420:80


networks:
  internal:
    driver: bridge
